services:
  db:
    image: postgres:16.1
    container_name: stats_data
    restart: unless-stopped
    ports:
      - "5433:5433"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/stats_data
    environment:
      POSTGRES_DB: stats_db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $POSTGRES_DB -U $POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 10